

DROP TABLE IF EXISTS TBL_FORMULA_INGREDIENTS;
CREATE TABLE TBL_FORMULA_INGREDIENTS (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    ingredient_id INT,
    min DOUBLE,
    max DOUBLE,
    result DOUBLE
);

 --ALTER TABLE TBL_FORMULA_INGREDIENTS
  -- ADD FOREIGN KEY (ingredient_id)
   -- REFERENCES TBL_INGREDIENTS(id);

DROP TABLE IF EXISTS TBL_FORMULA_NUTRIENTS;
CREATE TABLE TBL_FORMULA_NUTRIENTS (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    nutrient_id INT,
    min DOUBLE,
    max DOUBLE,
    result DOUBLE
);

DROP TABLE IF EXISTS TBL_INGREDIENT_NUTRIENTS;
CREATE TABLE TBL_INGREDIENT_NUTRIENTS (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    ingredient_id INT,
    nutrient_id INT,
    value DOUBLE NOT NULL
);

DROP TABLE IF EXISTS TBL_NUTRIENTS;
CREATE TABLE TBL_NUTRIENTS (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    code VARCHAR(250) UNIQUE,
    name VARCHAR(250) NOT NULL
);

DROP TABLE IF EXISTS TBL_INGREDIENTS;
CREATE TABLE TBL_INGREDIENTS (
    id INT AUTO_INCREMENT  PRIMARY KEY,
    code VARCHAR(250) UNIQUE,
    name VARCHAR(250) NOT NULL,
    price DOUBLE NOT NULL
);
